### ISSUE TITLE
Provide more explicit usage examples for CLI

### ISSUE THREAD

**Issue by bogdan-calapod** [smartprocure/directory-metagen#41]
Hello,

I've been toying around with metagen but can't get it to work - it always outputs an empty file. My hunch is that somehow I am not putting the path correctly - running from CLI it throws out a "folder not found" error, and running from package.json the same command runs but generates an empty file.

I think it would help a lot if the README would include more info on how the `path` is processed (relative to script directory ? relative to current folder ? absolute?)

**Comment by daedalus28** [comment]
Hi there!

Here's an example of how we're using the CLI in the package.json of one of our apps:

```js
    "metagen": "metagen src/pages/ deepES6",
    "metagen-watch": "metagen src/pages/ deepES6 --watch",
```


The relevant part of the directory structure of the project looks like this (it's a create-react-app repo with a "pages" directory in src)

```
/
  src/
    pages/
      page1.js
      page2.js
      ....
  public/
    ....
  package.json
```

The path is just passed along into [recursive-readdir](https://www.npmjs.com/package/recursive-readdir) here https://github.com/smartprocure/directory-metagen/blob/master/index.js#L15

So it should be relative to where it's executing from.

**Comment by sadasant** [comment]
Hi! About the CLI:

The path is relative to your current working directory, but it should work with an absolute path too.

The path is sent as the first parameter to the CLI (without considering the options, which are preceded either by `-` or by `--`).

For example, if your current directory is like:

```
src/
    pages/
        page1.js
public/
...
```

You can run: `./node_modules/.bin/metagen src/pages/ deepES6`, and it will produce an `__all.js` file inside of `src/pages/`.

Let us know if you're experiencing any issue!

**Comment by bogdan-calapod** [comment]
Thanks for the speedy reply 

I tried running `./node_modules/bin/metagen src/components/TestComponent/folder` es6 and it complained that it can't find the folder. I ran this in the root folder of a CRA app - might be something on my system ?

OS: Windows 10 Fall Creators Update
Env: Node v.8.9.4, Windows Subsystem for Linux (Ubuntu)

**Comment by daedalus28** [comment]
I'd suggest putting it as a script in your package.json since you'll probably want to run it regularly anyway. We're using it that way in production on a couple of CRA apps so that should work.

**Comment by sadasant** [comment]
This might be an issue with the directory separator, unix-like systems use `/`, but windows uses `\`.

**Comment by sadasant** [comment]
@bogdan-calapod try using the full path. I would suggest debugging this by setting up a `try {} catch() {}` around https://github.com/smartprocure/directory-metagen/blob/master/index.js#L15 , let's see if you're able to spot the details of the issue.

I don't have a Windows machine near me right now to provide a more accurate help.

**Comment by sadasant** [comment]
@bogdan-calapod also, as an emergency measure, try using this inside of cygwin. It should work inside of cygwin.

**Comment by bogdan-calapod** [comment]
I tried using a full path but it still failed. I'm running it in WSL, so the path separator is not an issue (it's the same as /). Might be something with my local setup, will check more in depth tomorrow

**Comment by sadasant** [comment]
@bogdan-calapod I know it's usually complicated to change the source code of an opensource library, but since we're not near the resources to give you a better resource, I would appreciate if you can try to fix it. You can make a PR if you find it! 🌞

**Comment by daedalus28** [comment]
@bogdan-calapod did you try an npm script in your package.json?

**Comment by daedalus28** [comment]
@bogdan-calapod Did it work?

**Comment by bogdan-calapod** [comment]
Hello, sorry for the late reply, I've been caught up with some stuff

I've tried installing metagen globally and ran it in a directory with my SVG files. While it did find the directory (no ENOENT error in sight) the `__all.js` file it generated is empty:

```javascript
export default {}
```

I want to take a more in-depth look on this, but I'm afraid I won't get to it until next week. I'll update this issue as soon as I investigate more into this 😁
