### ISSUE TITLE
Should we output arrow functions?

### ISSUE THREAD

**Issue by sadasant** [smartprocure/directory-metagen#9]
I'm thinking this could look a bit better if we used es6+'s features, however, the output would be very limiting afterward (but it will still work for our use cases).

**Comment by daedalus28** [comment]
What would have arrow functions? The AMD output? AMD shouldn't use arrows because it's likely targeting an older environment - but we could easily make it an option since the formatters are just functions

**Comment by sadasant** [comment]
alright, making it optional is relevant enough? It could be left as it is.

**Comment by daedalus28** [comment]
Well our consumption of the generated AMD modules are not currently passed through babel, which means we can't consume AMD modules defined with arrow functions. But some people might want them, so it's fine as an option

**Comment by daedalus28** [comment]
Not doing this for AMD but an es6 function will be merged soon
